on:
  push:
    branches:
      - main

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Read VERSION
        id: read_version
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: Make PDF Document
        uses: shrink/actions-document-publish@v1
        id: make_document
        with:
          sources: 'Balanced_Employee_IP_Agreement.md'
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.read_version.outputs.version }}
          release_name: Release v${{ steps.read_version.outputs.version }}
          body: |
            > See [Changelog](CHANGELOG.md) for changes.
          draft: false
          prerelease: false
      - name: Attach PDF to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.make_document.outputs.pdf }}
          asset_name: 'Agreement.pdf'
          asset_content_type: application/pdf
      - name: Attach Markdown to Release
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: 'Balanced_Employee_IP_Agreement.md'
            asset_name: 'Agreement.md'
            asset_content_type: text/markdown
